# Generated by Django 3.2 on 2022-02-03 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=10, unique=True)),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'MR.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.')], default=1)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_husband', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.PositiveSmallIntegerField(choices=[(1, 'Married'), (2, 'UnMarried'), (3, 'Separated')], default=2)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'General'), (2, 'General(EWS)'), (3, 'SC'), (4, 'SEBC'), (5, 'ST')], default=1)),
                ('certificate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_issued_date', models.DateField(blank=True, null=True)),
                ('non_creamy_layer_no', models.CharField(blank=True, max_length=50, null=True)),
                ('non_creamy_layer_date', models.DateField(blank=True, null=True)),
                ('certificate_given_by', models.PositiveSmallIntegerField(choices=[(1, 'Mamalatdar'), (2, 'T.D.O(Taluka Development Officer)'), (3, 'District Dy. Director (DC)'), (4, 'District Social Welfare Officer (DO)')], default=None)),
                ('certificate_issued_from', models.ForeignKey(blank=True, db_column='certificate_issued_from_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_issued_from', to='core.state')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileDocuments',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('caste_certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('non_creamy_layer_certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('ews_certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiledocuments_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiledocuments_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiledocuments_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile Documents',
                'db_table': 'profile_documents',
            },
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('degree', models.PositiveSmallIntegerField(choices=[(1, '10'), (2, '12')], default=None)),
                ('institute_name', models.CharField(blank=True, max_length=256, null=True)),
                ('board_name', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, max_length=5, null=True)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('trials', models.IntegerField(default=0)),
                ('document', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationdetails_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationdetails_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationdetails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Education Details',
                'db_table': 'education_details',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactdetails_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactdetails_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_district', to='core.city')),
                ('profile', models.OneToOneField(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('state', models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_state', to='core.state')),
                ('taluka', models.ForeignKey(blank=True, db_column='taluka_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_taluka', to='core.city')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactdetails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contact Details',
                'db_table': 'contact_details',
            },
        ),
    ]
